#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void ClearEncoder(){
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
}

void Forward(){
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
}

void Backward(){
	motor[leftMotor] = -50;
	motor[rightMotor] = -50;
}

void StopRobot(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait10Msec(100);
}

void TurnLeft(){
	ClearEncoder();
	while(nMotorEncoder(rightMotor) < 225 ){
		motor[rightMotor] = 30;
		motor[leftMotor] = - 30;
	}
}

void TurnRight(){
	ClearEncoder();
	while(nMotorEncoder(leftMotor) < 225){
		motor[leftMotor] = 30;
		motor[rightMotor] = - 30;
	}
}


task main(){
	int boxCount = 0;
	int iterationCount = 0;

	ClearEncoder();

	while(iterationCount != 3){

		Forward();
		wait1Msec(700);

		while(SensorValue(lightSensor) > 51.5){
				Forward();
		}

		StopRobot();
		Backward();
		wait1Msec(490);

		TurnLeft();
		StopRobot();

		if(SensorValue(sonarSensor) <= 35){
			boxCount++;
		}

		TurnLeft();
		TurnLeft();

		StopRobot();
		if(SensorValue(sonarSensor) <= 35){
			wait10Msec(100);
			boxCount++;
		}

		TurnLeft();
		StopRobot();

		iterationCount++;
	}

	nxtDisplayBigStringAt(49,21, "%d", boxCount);
	wait10Msec(1000);
}
