#pragma config(Sensor, S2,     ultraSonic,     sensorSONAR)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void Forward(){
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
}

void Backward(){
	motor[leftMotor] = -50;
	motor[rightMotor] = -50;
}

void TurnRight(){
	motor[rightMotor] = 0;
	motor[leftMotor] = 30;
	wait10Msec(300);
}

void TurnLeft(){
	motor[rightMotor] = 30;
	motor[leftMotor] = 0;
	wait10Msec(300);
}


task main()
{
	int count=0;
	while(count < 7){
 		if(SensorValue(ultraSonic) >  12){
 	  	Forward();
 		}
 		else{
 			if( count %2 == 0){
 				Backward();
 				wait1Msec(400);
 				TurnRight();
 				count ++;
 			}
 			else{
 				Backward();
 				wait1Msec(400);
 				TurnLeft();
 				count++;
 			}
 		}
	}
}
