#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void ClearEncoder(){
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
}

void Forward(){
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
}

void Backward(){
	motor[leftMotor] = -50;
	motor[rightMotor] = -50;
}

void StopRobot(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait10Msec(100);
}

task main(){
	int temp = 0;

	//line one
	while(SensorValue(lightSensor) > 51.5)
		Forward();
	StopRobot();

	temp = nMotorEncoder(rightMotor);
	while(nMotorEncoder(leftMotor) != 0)
		Backward();
	ClearEncoder();


	//line two
	while(nMotorEncoder(leftMotor) <= temp + 600)
		Forward();
	StopRobot();

	temp = nMotorEncoder(rightMotor);
	while(nMotorEncoder(leftMotor) != 0)
		Backward();
	ClearEncoder();

	//line three
	while(nMotorEncoder(leftMotor) <= temp + 620)
		Forward();
	StopRobot();

	temp = nMotorEncoder(rightMotor);
	while(nMotorEncoder(leftMotor) != 0)
		Backward();
	ClearEncoder();

}
