#pragma config(Sensor, S1, lightSensor, sensorLightActive)
#pragma config(Motor, motorA, leftMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor, motorB, rightMotor, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
void ClearEncoder(){
nMotorEncoder[leftMotor] = 0;
nMotorEncoder[rightMotor] = 0;
}
void StopRobot(){
motor[leftMotor] = 0;
motor[rightMotor] = 0;
wait10Msec(100);
}

void Right(){
ClearEncoder();
while(nMotorEncoder[leftMotor] < 445){
motor[leftMotor] = 50;
motor[rightMotor] = 0;
}
}

void Fwd(){
motor[leftMotor] = 50;
motor[rightMotor] = 50;
}
void srt(int x){
ClearEncoder();
while(nMotorEncoder(leftmotor)<x && nMotorEncoder(rightmotor)){

motor[leftMotor] = 50;
motor[rightMotor] = 50;
}
Fwd();
wait10Msec(80);
Right();

}


task main()
{
int count = 0;
while(count < 16)
{
while(SensorValue(lightSensor)>51.5)
{
Fwd();
}
if(SensorValue(lightSensor)<51.5)
{
srt(500);

count++;
}
clearencoder();
stoprobot();
}
}
