#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void ClearEncoder(){
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
}

void StopRobot(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait10Msec(100);
}


void Forward(){
		ClearEncoder();
		while(nMotorEncoder[rightMotor] < 700){
			motor[rightMotor] = 50;
			motor[leftMotor] = 50;
		}
}


void TurnRight(){
	ClearEncoder();
	while(nMotorEncoder[leftMotor] < 435){
		motor[leftMotor] = 50;
		motor[rightMotor] = 0;
	}
}


task main(){
	int count = 0;

	while(count <= 16){
		Forward();
		StopRobot();
		TurnRight();

		count++;
	}

	StopRobot();
}
