#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Forward(){
	motor[leftMotor] = 40;
	motor[rightMotor] = 40;
}

void TurnRight(){
	motor[rightMotor] = 0;
	motor[leftMotor] = 30;
	wait10Msec(155);
}


task main(){
	int count = 0;

	while(count <= 4){
		Forward();
		wait10Msec(150);

		TurnRight();

		Forward();
		wait10Msec(150);

		TurnRight();

		Forward();
		wait10Msec(150);

		TurnRight();

		count ++;
	}

	Forward();
	wait10Msec(150);

	TurnRight();

}
