#pragma config(Sensor, S1,     lightsensor,    sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void ClearEncoder(){
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;
}

void Forward(){
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;
}

void Backward(){
	motor[leftMotor] = -50;
	motor[rightMotor] = -50;
}

void StopRobot(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait10Msec(100);
}

void TurnLeft(){
	ClearEncoder();
	while(nMotorEncoder(rightMotor) < 220 ){
		motor[rightMotor] = 30;
		motor[leftMotor] = - 30;
	}
}

void TurnRight(){
	ClearEncoder();
	while(nMotorEncoder(leftMotor) < 220){
		motor[leftMotor] = 30;
		motor[rightMotor] = - 30;
	}
}

task main(){
	srand(random(2000));
	int randomNum = 0;

	while(true){

		randomNum = random() % 3;

		if(SensorValue(lightSensor) > 51.5){
			switch(randomNum){
				case 0 : 	Forward();
									wait10Msec(100);
									break;

				case 1 : 	TurnLeft();
									wait10Msec(100);
									break;

				case 2 : 	TurnRight();
									wait10Msec(100);
									break;

				default : StopRobot();

			}
		}
		else{
			StopRobot();
			Backward();
			wait10Msec(100);
		}

	}
}
